apiVersion: v1
kind: Pod
metadata:
  name: olatmysql
  labels:
    purpose: mysql-openolat
spec:
  containers:
  - name: olatmysql
    image: egifadli/automationmysql:6
    command: ["mysqld"]
  restartPolicy: OnFailure
