FROM ubuntu:18.04

MAINTAINER egi fadli

RUN apt-get update -y

RUN apt-get install -y systemd apt-utils

RUN apt-get install -y mysql-server mysql-client libmysqlclient-dev

ENV MYSQL_ROOT_PASSWORD=egi

#ENV MYSQL_DATABASE=openolat

#ENV MYSQL_USER=openolat

#ENV MYSQL_PASSWORD=egi

